services:
  script22-api:
    image: ghcr.io/tohjuler/script22-api:latest
    restart: unless-stopped
    container_name: script22-api
    environment:
      BETTER_AUTH_SECRET: # openssl rand -base64 32
      BETTER_AUTH_URL: http://localhost:3000
      CORS_ORIGIN: http://localhost:3001
      DB_FILE_NAME: /app/db/db.sqlite
      # Keep this secret, it is used to encrypt the credentials in the database. 
      # If you change it, all credentials will be lost.
      CREDENTIALS_MASTER_KEY_B64: # openssl rand -base64 32
    ports:
      - "3000:3000" # The API
    volumes:
      - db:/app/db

  script22-web:
    image: ghcr.io/tohjuler/script22-web:latest
    restart: unless-stopped
    container_name: script22-web
    depends_on:
      - script22-api
    ports:
      - "3001:3001" # The UI

volumes:
  db:
