/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PathlessLayoutRouteRouteImport } from './routes/_pathlessLayout/route'
import { Route as PathlessLayoutIndexRouteImport } from './routes/_pathlessLayout/index'
import { Route as authSetupRouteImport } from './routes/(auth)/setup'
import { Route as authLoginRouteImport } from './routes/(auth)/login'
import { Route as PathlessLayoutHostsHostIdRouteImport } from './routes/_pathlessLayout/hosts.$hostId'

const PathlessLayoutRouteRoute = PathlessLayoutRouteRouteImport.update({
  id: '/_pathlessLayout',
  getParentRoute: () => rootRouteImport,
} as any)
const PathlessLayoutIndexRoute = PathlessLayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PathlessLayoutRouteRoute,
} as any)
const authSetupRoute = authSetupRouteImport.update({
  id: '/(auth)/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const authLoginRoute = authLoginRouteImport.update({
  id: '/(auth)/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PathlessLayoutHostsHostIdRoute =
  PathlessLayoutHostsHostIdRouteImport.update({
    id: '/hosts/$hostId',
    path: '/hosts/$hostId',
    getParentRoute: () => PathlessLayoutRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof PathlessLayoutIndexRoute
  '/login': typeof authLoginRoute
  '/setup': typeof authSetupRoute
  '/hosts/$hostId': typeof PathlessLayoutHostsHostIdRoute
}
export interface FileRoutesByTo {
  '/login': typeof authLoginRoute
  '/setup': typeof authSetupRoute
  '/': typeof PathlessLayoutIndexRoute
  '/hosts/$hostId': typeof PathlessLayoutHostsHostIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_pathlessLayout': typeof PathlessLayoutRouteRouteWithChildren
  '/(auth)/login': typeof authLoginRoute
  '/(auth)/setup': typeof authSetupRoute
  '/_pathlessLayout/': typeof PathlessLayoutIndexRoute
  '/_pathlessLayout/hosts/$hostId': typeof PathlessLayoutHostsHostIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/login' | '/setup' | '/hosts/$hostId'
  fileRoutesByTo: FileRoutesByTo
  to: '/login' | '/setup' | '/' | '/hosts/$hostId'
  id:
    | '__root__'
    | '/_pathlessLayout'
    | '/(auth)/login'
    | '/(auth)/setup'
    | '/_pathlessLayout/'
    | '/_pathlessLayout/hosts/$hostId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  PathlessLayoutRouteRoute: typeof PathlessLayoutRouteRouteWithChildren
  authLoginRoute: typeof authLoginRoute
  authSetupRoute: typeof authSetupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_pathlessLayout': {
      id: '/_pathlessLayout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PathlessLayoutRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_pathlessLayout/': {
      id: '/_pathlessLayout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PathlessLayoutIndexRouteImport
      parentRoute: typeof PathlessLayoutRouteRoute
    }
    '/(auth)/setup': {
      id: '/(auth)/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof authSetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/login': {
      id: '/(auth)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_pathlessLayout/hosts/$hostId': {
      id: '/_pathlessLayout/hosts/$hostId'
      path: '/hosts/$hostId'
      fullPath: '/hosts/$hostId'
      preLoaderRoute: typeof PathlessLayoutHostsHostIdRouteImport
      parentRoute: typeof PathlessLayoutRouteRoute
    }
  }
}

interface PathlessLayoutRouteRouteChildren {
  PathlessLayoutIndexRoute: typeof PathlessLayoutIndexRoute
  PathlessLayoutHostsHostIdRoute: typeof PathlessLayoutHostsHostIdRoute
}

const PathlessLayoutRouteRouteChildren: PathlessLayoutRouteRouteChildren = {
  PathlessLayoutIndexRoute: PathlessLayoutIndexRoute,
  PathlessLayoutHostsHostIdRoute: PathlessLayoutHostsHostIdRoute,
}

const PathlessLayoutRouteRouteWithChildren =
  PathlessLayoutRouteRoute._addFileChildren(PathlessLayoutRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  PathlessLayoutRouteRoute: PathlessLayoutRouteRouteWithChildren,
  authLoginRoute: authLoginRoute,
  authSetupRoute: authSetupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
